engines:
  duplication:
    exclude_paths:
      - "**/tests/**"
      - "test_**.py"
      - "tests/**"
    bandit:
      exclude_paths:
        - "**/tests/**"
        - "test_**.py"
        - "tests/**"
exclude_paths:
  - "**/tests/**"
  - "test_**.py"
  - "tests/**"
