repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      # - id: check-yaml
      - id: debug-statements
      # - id: name-tests-test
      - id: requirements-txt-fixer
      # - id: double-quote-string-fixer
  # - repo: https://github.com/asottile/add-trailing-comma
  #   rev: v1.3.0
  #   hooks:
  #     - id: add-trailing-comma
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.7.7
  #   hooks:
  #     - id: flake8
  - repo: https://github.com/pre-commit/pre-commit
    rev: v1.17.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.19.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.5.0
    hooks:
      - id: reorder-python-imports
        language_version: python3
