- id: autopep8
  name: autopep8
  entry: autopep8
  language: python
  "types": [python]
  args: ["--aggressive --aggressive --max-line-length=120"]
  require_serial: false
  additional_dependencies: []
- id: flake8
  name: Flake8
  description: This hook runs flake8.
  entry: flake8
  language: python
  types: [python]
  args: ["--config=setup.cfg"]
  require_serial: true
