dist: trusty
language: python

cache:
  pip: true
  apt: true

python:
  - "3.6"

addons:
  apt:
    packages:
      # These are all for wxPython 4
      - libwebkitgtk-3.0-dev
      - libjpeg-dev
      - libtiff-dev
      - libgtk2.0-dev
      - libsdl1.2-dev
      - libgstreamer-plugins-base0.10-dev
      - freeglut3
      - freeglut3-dev
      - libnotify-dev

sudo: false

matrix:
  # jobs
  include:
    # linux - 3.7
    - env: Image=Linux_37
      python: 3.7
      dist: xenial
    # windows10 - 3.7
    - env:
        - Image=Win10_37
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
      os: windows
      language: shell
      before_install: choco install python
    # flake8
    - env: TEST=flake
      os: linux
      python: 3.6
      # coverage
    - env: TEST=coverage
      os: linux
      python: 3.6

before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - SRC_DIR=$(pwd)
  - echo $SRC_DIR
  - ls || dir

# https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.6-cp36-cp36m-linux_x86_64.whl
install:
  - pip install --upgrade pip || pip3 install --upgrade pip
  - pip install -r requirements_origami_travis.txt
  - if [[ "${Image}" == "Linux_37" ]]; then
    pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython;
    elif [[ "${Image}" == "Win10_37" ]]; then
    pip install -U wxPython;
    fi;

  # install test dependencies
  - if [[ "${TEST}" == "flake" ]]; then
    pip install flake8;
    elif [ "${TEST}" == "coverage" ]; then
    pip install codecov pytest==3.6 pytest-cov pytest-sugar pytest-travis-fold;
    elif [ "${Image}" == "Win10_37" ]; then
    pip install setuptools;
    fi;
  - cd ${SRC_DIR}
  - cd origami

script:
  - echo $SRC_DIR
  - if [[ "${TEST}" == "flake" ]]; then
    flake8;
    elif [[ "${TEST}" == "coverage" ]]; then
    py.test --cov;
    elif [[ "${Image}" == "Win10_37" ]]; then
    python3 ORIGAMI.py || python ORIGAMI.py;
    elif [[ "${Image}" == "Linux_37" ]]; then
    python3 ORIGAMI.py || python ORIGAMI.py;
    fi;

notifications:
  email: false
