build: false

cache:
  - '%LOCALAPPDATA%\pip\Cache'

platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:/Python36"
      MINICONDA: C:\Miniconda36-x64
      PYTHON_ARCH: 64
      PYTHON_VERSION: "3.6"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA% %PYTHON_ARCH%"

install:
  # set environment
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  # print environment information
  - pip --version
  # install conda
  - conda update --yes --quiet conda
  - conda create -n testenv --yes
  - activate testenv
  - python -m pip install --upgrade pip
  - pip install -r requirements/requirements-std.txt
  - pip install -r requirements/requirements-dev.txt
  - pip install -r requirements/requirements-win32.txt
  - pip install -U wxPython;
  - python setup.py develop

test_script:
  - activate testenv
  - pytest .

matrix:
  fast_finish: true
