version: 2
jobs:
    build:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout
        - run:
            name: install apt packages
            command: |
                sudo apt-get update
                sudo apt-get install -y libgtk-3-dev libjpeg-dev libtiff-dev \
                        libsdl2-dev libgstreamer-plugins-base1.0-dev libnotify-dev \
                        libsm-dev libwebkit2gtk-4.0-dev libxtst-dev \
                        libgl1-mesa-dev libglu1-mesa-dev python-virtualenv

        - run:
            name: Setup Python environment
            command: |
            - pip install -U pip wheel
            - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython
            - pip install -r specml_requirements.txt
        - run:
            name: Build specML
            command: |
              python specML.py