# -*- coding: utf-8 -*-

# -------------------------------------------------------------------------
#    Copyright (C) 2017 Lukasz G. Migas <lukasz.migas@manchester.ac.uk>
# 
#	 GitHub : https://github.com/lukasz-migas/ORIGAMI
#	 University of Manchester IP : https://www.click2go.umip.com/i/s_w/ORIGAMI.html
#	 Cite : 10.1016/j.ijms.2017.08.014
#
#    This program is free software. Feel free to redistribute it and/or 
#    modify it under the condition you cite and credit the authors whenever 
#    appropriate. 
#    The program is distributed in the hope that it will be useful but is 
#    provided WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
# -------------------------------------------------------------------------


#----------------------------------------------------------------------
# Bitmap images were generatred using: img2py png py
# In case of issues (bKGD invalid or similar) use convert bad.png good.png 

from wx.lib.embeddedimage import PyEmbeddedImage

add_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFz"
    "UkdCAK7OHOkAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAGXRFWHRT"
    "b2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAEJJREFUOE9j/PDhw38GCgATlCYbDHID"
    "BAQEwBgfGHgvYEQjIScD1UNZEEB9FyADmGvQbUUGgzAQSQUD7wUKDWBgAAA0aRW5ed/Q4wAA"
    "AABJRU5ErkJggg==")
getAdd16 = add_16.GetBitmap()

remove_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFz"
    "UkdCAK7OHOkAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAGXRFWHRT"
    "b2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAADRJREFUOE9j/PDhw38GCgATlCYbjBpA"
    "BQMwolFAQADKwg6A6qEsCKC+C0gFo9E48AYwMAAAYzcOi9PpUgUAAAAASUVORK5CYII=")
getRemove16 = remove_16.GetBitmap()

extract_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFz"
    "UkdCAK7OHOkAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAGXRFWHRT"
    "b2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAg9JREFUOE+Vk8+LqWEUx7/vexkmkzKk"
    "MTZYzAJpNlKk2arZKKVYK5bzD+Am/gCrmaaUZjc2xEJIagrZ2VjJTEJK+dUQjcZ7PY93pmbm"
    "1r0+9dR5zznvec5zfjCz2YzDgRQKBVSrVUQiEbC87r/ZbrdoNBqQy+VoNpuHB+h2uzCbzfD7"
    "/UilUocHILy9vaFUKqHX64G5u7vjXl5eeNO/eX19xXq9phnk83kwLpeLu7m5wdnZGQQCAe+2"
    "Zz6f0zfLZDJeA0wmE7Asi8vLS4TDYTCtVouLxWLQ6/VQKBS8G5BOp+F0OqmcyWQ+ZUK73cbx"
    "8TGEQiEEarUadrsdDofjy02dTgeBQIDKz8/P8Hg8VO73+1Aqlbi6ukI8Hgf78PCAYrGI0WiE"
    "p6cn6kQYDAY0fXKI/MH7+zsWiwVI3U5PT8GS6MlkkrbmIwAplFgshs/nw+PjI0QiEdURjEYj"
    "arUa7u/v4Xa78ctisfyu1+sol8vQaDQwmUzIZrOQSqU4OTnBdDrFarXCcrmEwWCgLdTpdDTj"
    "6+trgIzy9+P1erldi7gPotEot7vt075Ln7u9vaW2H4MkkUig1WoxHo9B2pvL5WhmFxcX1Pad"
    "HwHIkthsNjAMQ+eiUqlgs9nAarVS23e+BDg6OqKbRn4gcjAYpMNCapFIJGhtiP78/Hz//h1f"
    "1jkUCkGlUvFff2c4HNL+7wH+APpDB84HIeyhAAAAAElFTkSuQmCC")
getExtract16 = extract_16.GetBitmap()

save_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AADaSURBVDiNrZK9DkFBEIW/8ZMoVCqNRCGIaHTeQqVReQSJhlbDQ0i0HkHiBXQaxY1eoZQo"
    "JUdhb7K4WOEkk83OzpyZM7MGRECNG7bAntfIAR1gJmkcOyNAzgaS8A1IA32gBxS92KkkMm+q"
    "xcgCC+AE1D3/yMwuqQCCd+iGdCDg6Dp4wiNBwczKCXFtd5aSSPwhfmvRrzO4k3AA5gE5eWDo"
    "O2IJG7f3KjfNzcc/4d79vxAlbaHlgs7A7hsJMWpAA8DMGsBa0iqYQNLkU1UfP2/hr2usmNky"
    "ICfnX658BVigXx2yfwAAAABJRU5ErkJggg==")
getSave16 = save_16.GetBitmap()

open_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAEISURBVDiNxdMtS4RREAXgZ0SzH2GLFg0GMfgRFmGTSZMY/Ak2f4KCQdBikfUfWLVuswva"
    "LaKCQQyioCyCMAbfXV5kZVc2eGDK3HvOzDmXG5mpHwz0xcZARFQj4jwiHou6iYidv4hcYgtz"
    "RS3hGrXM1K0CidHMfGkpRkQdK3j4MewCh5n51L77i8AYasV5GRtoZuZmuZkY6WXdwuJtuTdY"
    "VoqIwBoWMdQhrwrGIuIATZy2LeAdZ5hCA58dBMoYx3J5g2MMYyEzP7qQRcQuJloZbOMelR6z"
    "WMczplsCb5jvkTyLV6y2QrzCHTIi5rpsPokj7GVmg+93rmIfM918F4PqmXnSzuLff+MX+vO/"
    "I/WJvDwAAAAASUVORK5CYII=")
getOpen16 = open_16.GetBitmap()

bin_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFz"
    "UkdCAK7OHOkAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAGXRFWHRT"
    "b2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAARFJREFUOE+tkzGuRFAUhn8aCcV09qDV"
    "2obeHigUah02wgoUOqsQG9AgQqJgJsc7x3szickkb77k5tzz+/25bhxlGIY7XsjzHG3bcgf0"
    "fY8kSbBtGyu/HAFd16Gua5aAoijgui53QNM0mKYJtm2zAjiOA9M0fwJUVUUQBPB9nx+/J8sy"
    "pGmKfd8BCqAVhuH9U8gr76kc+kRZlkelo9MiRHvlDFAUhXdAVVVHpYuUyxSN+Os9AzRNw7qu"
    "3F1DHvIKZ4BhGJjnmbtryENe4XsBuq5/HEBe4bufsCwLd9eQ5zLg3yeQAMuyjkr/Oi1CtMuA"
    "2+2GcRyPved5R6XhkQESjTzkFZ7GOY5j0GC9gwYoiiLugAd58cM5mdVJHAAAAABJRU5ErkJg"
    "gg==")
getBin16 = bin_16.GetBitmap()

overlay_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAAAAAA6mKC9AAAABGdBTUEAALGPC/xhBQAAACBj"
    "SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8A"
    "AAAJcEhZcwAADsQAAA7EAZUrDhsAAAAHdElNRQfhBQ8KLyHSrVBEAAAAm0lEQVQY04XPIW4C"
    "YQBE4Y9NJeI/BQLXO1DXQ1T1GshquAA36AVYt5saBIJ0QzhB5UBwEFKxQELSpCNHzHsziMdU"
    "/ii6UgqllA5yYH1qWZ7WHCJWydb+Q5usBEk0r5+NJFTObNSLXW3DWeVIzduImuMdO13csUMm"
    "zOZMGLqNti/X0R777f3Htsf2Yg1tL/bkku6ZKHyNLwb/vv0FnShNumVamewAAAAldEVYdGRh"
    "dGU6Y3JlYXRlADIwMTctMDUtMTRUMTE6Mjg6NTUrMDE6MDDb++yRAAAAJXRFWHRkYXRlOm1v"
    "ZGlmeQAyMDE3LTA1LTE1VDEwOjQ3OjMzKzAxOjAwZVmxSgAAABl0RVh0U29mdHdhcmUAd3d3"
    "Lmlua3NjYXBlLm9yZ5vuPBoAAAAASUVORK5CYII=")
getOverlay16 = overlay_16.GetBitmap()

compare_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFz"
    "UkdCAK7OHOkAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAGXRFWHRT"
    "b2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAbdJREFUOE+lU7/L8VEU/zxfv/IrA5F/"
    "gMFiUBYppWxG2ZiVrAZFSckiJptitFkYDP4Ai0nZKAxSEvL7+zznuD2e9315Dc+nbvfcc889"
    "93PP59yP9Xot4xd4m0Cn0yGVSmG/30OtVqNcLuNyuYhdQBLzS+x2O5zPZ9RqNej1eiwWC7Fz"
    "x1sGsizD7/fDbDbDYrGwT6PRoFgswmg0vmfQbDYRCASQTqdhMpnQaDSQz+cRj8dxOByeM5jN"
    "ZojFYnzjdDpFpVJBu91GoVDA7XbjmPl8jmq1+jzBaDRCv9+Hy+XiBJQwkUgw5Z+gS76fQG/t"
    "dDo8er0e++x2O/tDodA/hwkKheKRoNvtYjAYiNUdHo8Hw+EQbrdbeB5YrVaw2Wx/FtHn8yEa"
    "jSIYDAoP+BmlUgkGg0F47tJSb+RyOSiXyyW22y0mkwmcTqcIeYCq7fV6MR6PYbVaOZblkyR8"
    "1Q9SJBJh+kT1FUjGVqsFpVKJTCbDatTrdWSzWUgOh4M1DofDIvw1tFotVCoV21RA6k6JdKWG"
    "oHalQfbpdOJ+J/t4POJ6vbJN89/4SCaT8mazEcv/49ln+uV3Bj4Bu9rTybaCvcIAAAAASUVO"
    "RK5CYII=")
getCompare16 = compare_16.GetBitmap()

plot_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAFz"
    "UkdCAK7OHOkAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAGXRFWHRT"
    "b2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAAZNJREFUOE+dk0+rAVEYxh+zEUX+1Cwk"
    "FrKRhZKsKTtL+QZTlL2avS9gYeMLWNhbsEOxsmAjpSzYSEhR/h1z3jnuNbn3cv3q7bzvM2/P"
    "mfOeGZPf72f5fB65XA6fIM1mM6zXa1H+jtlshsViEdU3klj/ZLvdwuv1UhwOB6HqvGUwHo+x"
    "Wq2wXC4xmUyEqvPSYLFYQJZllMtlVCoVnM9nnE4n8fQHA37OTqdDTfP5HKFQCJFIBPF4nGaV"
    "TCYRi8Vgs9mo/8lAVVWk02kkEglcr1ehgvJ7/ag/GUiSLvE1HA5jMBig3+9jOBzC4/Gg0Wig"
    "1+tht9tRH4cVi0W22WwotDOyVqvFut0uy2QyrFarsWazyXgfj3a7/dXLw/AGfNdqtQq3200D"
    "q9frKBQKCAaDsNvtcDqdCAQColvHYFAqlcC/ylQqBW13undFUeBwOGigPKxWq+jWMRjc3X0+"
    "Hw1xNBpBOx5pl8sFx+OR8kcMBtlsFtPplIb0LgYDjsvlwn6/F9VrTFowfl3RaFRX/gn9ziL/"
    "AOAG7hytkpNhvt8AAAAASUVORK5CYII=")
getPlot16 = plot_16.GetBitmap()

link_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAAAAAA6mKC9AAAABGdBTUEAALGPC/xhBQAAACBj"
    "SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8A"
    "AAAJcEhZcwAADsQAAA7EAZUrDhsAAAAHdElNRQfhBQ4MBwPmoaTdAAAA5klEQVQY0z2PsUtC"
    "URyFv3tvPdEUgiDHCLdwqcmhmqyH+h9IDS6+vaZHS/9Bc0OT1dSoWfTGgpqChoKWhmbhB+IN"
    "3vNpw7v1befjDOcgf/yElWX/VTSO2fZ1cOnVvpRkeb6Xv03hMHYNzy8OUyB4ccLuDqYA7ytK"
    "gKWzYbxzkoKptpUAzc9O6aJ6hWnYJyXM94v9hJJNTWMSGc2sXugnMM4yOlcvDBJqxx+9LRsZ"
    "IFwbi8j9pikfTUREVCXoAnjf5WyAHm0ALDRP3QXlez0wLRs5YW7Ct9W7zuKDckKvP8cH5+3H"
    "/9e/y6JWEbRnR2sAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTctMDUtMTRUMTI6MDc6MDMrMDE6"
    "MDDkZllNAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE3LTA1LTE0VDEyOjA3OjAzKzAxOjAwlTvh"
    "8QAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAAASUVORK5CYII=")
getCombine16 = link_16.GetBitmap()

process_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAAAAAA6mKC9AAAABGdBTUEAALGPC/xhBQAAACBj"
    "SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8A"
    "AAAJcEhZcwAADsQAAA7EAZUrDhsAAAAHdElNRQfhBQ8KKQNRl7YmAAAArklEQVQY013OMUoD"
    "YRQA4e//2RAjidiJhYV3ELyEx8wxPIMgpgkKooIBC/MwuxrdmGcRQXCqYaop4Y/5+fSiBIyG"
    "6LtDosG48TYRA1yq7DddbkoZ5NL2jKDf8PXBtjUNYTb3kpn55NkyhMQ6s8W3qJCrvVLG64VK"
    "A8ZZ5O6l+kdlpez8+OoB0UsW3JuliEZ3UzIrp6k8Ujm5Lu/ZfuZruT2gBIYjsGn9BtwdTXby"
    "Ay1VTpa8he6tAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE3LTA1LTE1VDEwOjM1OjU5KzAxOjAw"
    "W9WagQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxNy0wNS0xNVQxMDo0MTowMyswMTowMObIxu4A"
    "AAAZdEVYdFNvZnR3YXJlAHd3dy5pbmtzY2FwZS5vcmeb7jwaAAAAAElFTkSuQmCC")
getProcess16 = process_16.GetBitmap()

 
idea_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAA3NCSVQICAjb4U/gAAAACXBI"
    "WXMAAAQuAAAELgEvgvcBAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAA"
    "AH5QTFRF/////6pV/79A789Qm5tk7s1I8MxN8M5K8cxK7s1L785J8M5I785L7s5L785J789K"
    "7s5J8M9K785K6stL8M5K789K8M5J781K785Kh4Nu785K785KYWl8VWCA6stM785K785L789O"
    "8NBS8NFT8NJX8tht8thu9N6F9d+G9d+IomfScgAAAB10Uk5TAAMEEBcuMjQ3PT9DTlheYGl1"
    "fISXnqevsMDL9v2OZHANAAAAfklEQVQYGVXBBxaCMBAFwE/ovSMhhBUL6v0vKG6iD2dgpSn+"
    "hSF+ghIQvi+AMgDLRaPOpBqRwxquj+eFaICVra8bfWQw+m0j1mMXd+50X4lNbhdjdyJrhFGQ"
    "VcBwRmKjAyNBpYhUhQQsqoF2WVqgjvAltZY4klpLHHnz7IG9AeD/C1JdA2nuAAAAAElFTkSu"
    "QmCC")
getIdea16 = idea_16.GetBitmap()

success_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAA3NCSVQICAjb4U/gAAAACXBI"
    "WXMAAARuAAAEbgHQo7JoAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAA"
    "AGxQTFRF////AP//KK6GJK2JJK+JJq2HJa6HJa+JJa6IJa6IJa6IJq6IKK+JKK+KK7CLLrGN"
    "M7OPNLOQNbSRObWTPLeVQLiWRLmZRrqaVsCjY8WqacetgNC5htK9j9XCltjGndrJruHTtuTX"
    "ueXZvufcQhO/KQAAAAp0Uk5TAAEmcH+As7Xm9myQZpsAAAB3SURBVBhXZY9HEgMhEAMFLLPQ"
    "zjnH/f8ffcCmtkzfNFXSSJIkHy0li14FFzIA5OAkyfVUeicpMCJIPle1XZG9YtXLYQOd7Kfn"
    "7wNgSjBbAJPnESApwW7Yw+NMORiwfp2ul2K0Ejq9375J3fgtkH1brK3ejPub/wG/CwjxA06B"
    "TgAAAABJRU5ErkJggg==")
getSuccess16 = success_16.GetBitmap()

error_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAA3NCSVQICAjb4U/gAAAACXBI"
    "WXMAAARuAAAEbgHQo7JoAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAA"
    "ADNQTFRF/////wAA11dK1ltL11pK11pK11pK2FpL11pK11pK11pK11tL22pb8cbB8svG89DL"
    "9NDMNsZlDQAAAAp0Uk5TAAEmcH+As7Xm9myQZpsAAABhSURBVBhXZY+BDoAgCERREpEo/f+v"
    "TShbizfm4PQEACa5EDOVDDcJmzgNk9dVXqopKB9w+u39Ls/RMhRLDxXRw5QNyC711BmWEbB7"
    "dXSvhZfQxxKCJXwa2obB4uhhud/6Fza7B+3BJRkkAAAAAElFTkSuQmCC")
getError16 = error_16.GetBitmap()

blank_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQAAAAA3iMLMAAAABGdBTUEAALGPC/xhBQAAACBj"
    "SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAd2KE6QA"
    "AAAJcEhZcwAADsQAAA7EAZUrDhsAAAAHdElNRQfhBRMKNwQBffR9AAAADklEQVQI12P4/5+B"
    "FAQA/U4f4XOLpqwAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTctMDUtMTlUMTA6MjQ6NDArMDE6"
    "MDCLibj6AAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE3LTA1LTE5VDEwOjU1OjA0KzAxOjAwTChU"
    "EgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAAASUVORK5CYII=")
getBlank16 = blank_16.GetBitmap()

blankTrans_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQAAAAA3iMLMAAAAAnRSTlMAAQGU/a4AAAAJcEhZ"
    "cwAAAEgAAABIAEbJaz4AAAAOSURBVAjXY/j/n4EUBAD9Th/hc4umrAAAACV0RVh0ZGF0ZTpj"
    "cmVhdGUAMjAxNy0wNS0xOVQxNDo1MzoyOS0wNDowMDKng+0AAAAldEVYdGRhdGU6bW9kaWZ5"
    "ADIwMTctMDUtMTlUMTQ6NTM6MjktMDQ6MDBD+jtRAAAAAElFTkSuQmCC")
getBlankTrans16 = blankTrans_16.GetBitmap()

blankTrans_1 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAAQCAQAAAB9lt08AAAABGdBTUEAALGPC/xhBQAAAAJi"
    "S0dEAP+Hj8y/AAAACXBIWXMAAABIAAAASABGyWs+AAAAB3RJTUUH4QUTDxUgnAeUZwAAAA9J"
    "REFUCNdj+M/AxEACAgAx0QEeuq1jlwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAxNy0wNS0xOVQx"
    "NToyMTozMiswMTowMO3V2J0AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMTctMDUtMTlUMTU6MjE6"
    "MzIrMDE6MDCciGAhAAAAAElFTkSuQmCC")
getBlankTrans1 = blankTrans_1.GetBitmap()

info_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAABGdBTUEAALGPC/xhBQAAACBj"
    "SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAKqNIzIA"
    "AAAJcEhZcwAADdcAAA3XAUIom3gAAAAHdElNRQfhBRQWFQ+59gl4AAAAzUlEQVQoz43RL0sE"
    "YRDH8c+uFxSuGOS64aKGPSxWQV+Dr2KTVYtvw7i2awsmwe4iKBgEsV0QLIJ7Bv8Fbx9ng+JM"
    "+v7m98wMz2S6GNtXKNBoVO6EyJRanyFbpeynXPeKXdadpQzitQ3Hicrv2bH5CbbCoDFHvbbv"
    "zj0GPhwo0qqtqRs71sL6E2bJfa+SW/YcOswGwb1uhDdRk2sCXfiwbSUoTd9wht343mWuMk/4"
    "gFWviedOlzx5sbcQRm5dGdpc8IH6X1/957GS57dzfwFzY3i20JqhLQAAACV0RVh0ZGF0ZTpj"
    "cmVhdGUAMjAxNy0wNS0yMFQyMjoyMToxNSswMjowMPcROFkAAAAldEVYdGRhdGU6bW9kaWZ5"
    "ADIwMTctMDUtMjBUMjI6MjE6MTUrMDI6MDCGTIDlAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5r"
    "c2NhcGUub3Jnm+48GgAAAABJRU5ErkJggg==")
getInfo16 = info_16.GetBitmap()